GET http://localhost:3333/jokes
###
GET http://localhost:3333/jokes/6217aebc92f24159e94ec227
###

POST http://localhost:3333/jokes/
Content-Type: application/json

{
"text": "This is the best joke of John.",
"author": "6217ae4592f24159e94ec21e"
}

###
PATCH http://localhost:3333/jokes/62179ca19c1ecb50e44645e2
Content-Type: application/json

{
"text": "This is changed again.",
"author": "Andrea"
}

###
DELETE http://localhost:3333/jokes/6217aebc92f24159e94ec227


###
GET http://localhost:3333/people
###
GET http://localhost:3333/people/6217aa756c9119610ed066bf
###

POST http://localhost:3333/people/
Content-Type: application/json

{
"name": "John Doe",
"email": "john@doe.com"
}

###
PATCH http://localhost:3333/people/6217aa756c9119610ed066bf
Content-Type: application/json

{
"name": "Jane Doe",
"email": "Jane@doe.com"
}


###
DELETE http://localhost:3333/people/6217a74956c32908a7da339e
